### ISSUE TITLE
Deploy example to GitHub Pages

### ISSUE THREAD

**Issue by hupf** [headwirecom/jsonforms-react-spectrum-renderers#11]
- [x] Create separate Webpack config and build example project
- [x] Setup Travis to deploy to GitHub Pages (`master` only)

**Comment by hupf** [comment]
@reusr1 I've updated the Travis config for the deployment of the example to GitHub pages:
- Can you provide a valid token via the `GITHUB_TOKEN` environment variable in Travis? I don't have sufficient privileges to do so.
- Once the build works: can you ensure the branch `gh-pages` is configured as the source in the GitHub pages section of the repository settings?

**Comment by reusr1** [comment]
@hupf I made you admin of the repo

**Comment by hupf** [comment]
@reusr1 The example will now automatically be deployed here: https://headwirecom.github.io/jsonforms-react-spectrum-renderers/
There is also a link in the README file.
