### ISSUE TITLE
Background Colors of Input Fields

### ISSUE THREAD

**Issue by mburri** [headwirecom/jsonforms-react-spectrum-renderers#47]
The backgrounds of input fields seem to be inconsistently colored - some are white, some are grey...

![image](https://user-images.githubusercontent.com/4577216/100710302-cd349200-33af-11eb-8392-2e049efddc75.png)

**Comment by hupf** [comment]
As @mburri already mentioned in the email, we did nothing special here. We just use the existing React Spectrum components, that implement the Adobe Spectrum design system.

In this example, the nationality is a [Picker component](https://spectrum.adobe.com/page/picker/), that has slightly gray background according to the Adobe Spectrum guidelines:

![image](https://user-images.githubusercontent.com/66047/100763209-270b7b00-33f5-11eb-8616-95b2db5c0f6b.png)

While the age is a [TextField component](https://spectrum.adobe.com/page/text-field/), that has a white background according to the Adobe Spectrum guidelines.

I suppose the gray background for the Picker component has been chosen intentionally, to distinguish it from the [ComboBox component](https://spectrum.adobe.com/page/combo-box/) (that has a white background). This helps to create an [affordance](https://www.interaction-design.org/literature/topics/affordances) that communicates to the user where he can write, and where he can't.

**Comment by reusr1** [comment]
closing - agree with you @hupf this is according to the spectrum guidelines
