### ISSUE TITLE
Example "oneOf (in array)": Expandable table rows with delete button

### ISSUE THREAD

**Issue by hupf** [headwirecom/jsonforms-react-spectrum-renderers#52]
With the vanilla renderer, an empty table with a plus button that does not work is rendered.

With the Material renderer, a table with expandable rows that contain the form, and a delete button on each row, is rendered:

![image](https://user-images.githubusercontent.com/66047/100869809-de5bcc80-349d-11eb-93e7-c25211462fdb.png)

With our Spectrum renderer we directly render the forms vertically, without the possibility to delete entries:

![image](https://user-images.githubusercontent.com/66047/100870123-5e823200-349e-11eb-8bba-7b1cdb64a4f8.png)

Should we add delete buttons? Should the forms be collapsable? Should we use a table layout?

**Comment by mburri** [comment]
We should not use tables.
We create a custom component (check out the group component for inspiration) and add a header toolbar with controls (delete, collapse icon)

**Comment by mburri** [comment]
fixed by #85
