### ISSUE TITLE
Example "Enums": One of enums

### ISSUE THREAD

**Issue by hupf** [headwirecom/jsonforms-react-spectrum-renderers#59]
With the vanilla renderer and the Spectrum renderer, the "One of Enums" in the "Enums" example are rendered as simple text fields. The Material renderer uses a combox/select to render them.

What does "One of Enum" mean an how should we implement it?

**Comment by mburri** [comment]
Combobox is currently in alpha: https://react-spectrum.adobe.com/react-spectrum/ComboBox.html

Check how the material renderers implement One of Enum
